---
- name: Creates directory
  file:
    path: "{{ docker_dir }}"
    state: directory

- name: Copy files
  copy:
    src: "{{ item.src }}"
    dest: "{{ docker_dir }}/{{ item.dest }}"
  with_items: "{{ files_to_copy }}"

- name: Start Docker Compose
  command: docker-compose -f "{{ docker_dir }}/docker-compose.yml" up --build -d
