---
- name: Ensure bin directory exists for Ansible user
  file:
    path: "/home/{{ ansible_user }}/bin"
    state: directory
    mode: '0755'

- name: Download yt-dlp binary
  get_url:
    url: https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp
    dest: "/home/{{ ansible_user }}/bin/yt-dlp"
    mode: '0755'
