---
- name: Backup existing sources.list
  ansible.builtin.command:
    cmd: cp /etc/apt/sources.list /etc/apt/sources.list.bak
  ignore_errors: yes

- name: Replace sources.list with new content
  ansible.builtin.copy:
    content: |
      deb https://deb.debian.org/debian bookworm main non-free-firmware
      deb-src https://deb.debian.org/debian bookworm main non-free-firmware

      deb https://security.debian.org/debian-security bookworm-security main non-free-firmware
      deb-src https://security.debian.org/debian-security bookworm-security main non-free-firmware

      deb https://deb.debian.org/debian bookworm-updates main non-free-firmware
      deb-src https://deb.debian.org/debian bookworm-updates main non-free-firmware
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: '0644'

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
