---
- name: Install Syncthing on Debian-based systems
  apt:
    name: syncthing
    state: present
  when: ansible_facts['distribution'] == 'Debian'

- name: Enable Syncthing service for the current user
  systemd:
    name: "syncthing@{{ username }}.service"
    enabled: yes
  when: ansible_facts['distribution'] == 'Debian'

- name: Start Syncthing service for the current user
  systemd:
    name: "syncthing@{{ username }}.service"
    state: started
  when: ansible_facts['distribution'] == 'Debian'
