---


- name: Update apt package index
  ansible.builtin.apt:
    update_cache: yes

- name: Install required packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
    state: present

- name: Get latest release info from GitHub
  uri:
    url: "https://api.github.com/repos/Mirantis/cri-dockerd/releases/latest"
    return_content: yes
  register: release_info

- name: Extract download URL for debian-bookworm_amd64.deb
  set_fact:
    download_url: >-
      {{ release_info.json.assets | selectattr("name", "search", "debian-bookworm_amd64.deb$") | map(attribute="browser_download_url") | list | first }}

- name: Download the Debian package from GitHub
  get_url:
    url: "{{ download_url }}"
    dest: /tmp/cri-dockerd.debian-bookworm_amd64.deb

- name: Install cri-dockerd
  ansible.builtin.apt:
    deb: /tmp/cri-dockerd.debian-bookworm_amd64.deb
    state: present

- name: Ensure /etc/apt/keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Kubernetes signing key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
    dest: /tmp/Release.key

- name: Convert Kubernetes signing key to GPG format
  ansible.builtin.command:
    cmd: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/Release.key
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Remove temporary key file
  ansible.builtin.file:
    path: /tmp/Release.key
    state: absent


- name: Add Kubernetes apt repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    content: |
      deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /

- name: Update apt package index after adding Kubernetes repository
  ansible.builtin.apt:
    update_cache: yes

- name: Install kubelet, kubeadm, and kubectl
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Pin kubelet, kubeadm, and kubectl versions
  ansible.builtin.command:
    cmd: apt-mark hold kubelet kubeadm kubectl

- name: Enable and start kubelet service
  when: auto_run
  ansible.builtin.systemd:
    name: kubelet
    enabled: yes
    state: started
