---
- name: Download the Mullvad signing key
  ansible.builtin.get_url:
    url: https://repository.mullvad.net/deb/mullvad-keyring.asc
    dest: /usr/share/keyrings/mullvad-keyring.asc
    mode: '0644'

- name: Add the Mullvad repository server to apt
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/mullvad-keyring.asc arch=amd64] https://repository.mullvad.net/deb/stable {{ ansible_distribution_release  }} main"
    state: present

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Mullvad VPN
  ansible.builtin.apt:
    name: mullvad-vpn
    state: present
