---
- name: Create a systemd override directory for getty
  file:
    path: /etc/systemd/system/getty@tty1.service.d
    state: directory
    mode: 0755

- name: Create an override file to enable auto-login
  copy:
    dest: /etc/systemd/system/getty@tty1.service.d/override.conf
    content: |
      [Service]
      ExecStart=
      ExecStart=-/sbin/agetty --autologin {{ auto_login_user }} --noclear %I $TERM
    mode: 0644
