---
- name: Gather facts
  ansible.builtin.setup:

- name: Install common packages on Debian-based systems
  ansible.builtin.apt:
    name:
      - git
      - vim
      - curl
      - htop
    state: present
  when: ansible_facts['distribution'] == 'Debian'

- name: Install common packages on Alpine-based systems
  ansible.builtin.apk:
    name:
      - git
      - vim
      - curl
      - htop
    state: present
  when: ansible_facts['distribution'] == 'Alpine'

- name: Install common packages on RHEL-based systems
  ansible.builtin.dnf:
    name:
      - git
      - vim
      - curl
      - htop
    state: present
  when: ansible_facts['distribution'] in ['RedHat', 'CentOS', 'Fedora', 'Rocky', 'AlmaLinux']
